const CLAMAV_DEFINITIONS_FILES = ['main.cvd', 'daily.cvd', 'bytecode.cvd'];
const CLAMAV_BUCKET_NAME       = 'clam-av-files-bucket';
const PATH_TO_AV_DEFINITIONS   = 'virus_definitions';
const PATH_TO_CLAMAV = './clamscan';
const STATUS_CLEAN_FILE = process.env.STATUS_CLEAN_FILE || 'CLEAN';
const STATUS_INFECTED_FILE = process.env.STATUS_INFECTED_FILE || 'INFECTED';
const STATUS_ERROR_PROCESSING_FILE = process.env.STATUS_ERROR_PROCESSING_FILE || 'ERROR';


module.exports = {
    CLAMAV_BUCKET_NAME          : CLAMAV_BUCKET_NAME,
    PATH_TO_AV_DEFINITIONS      : PATH_TO_AV_DEFINITIONS,
    PATH_TO_CLAMAV              : PATH_TO_CLAMAV,
    STATUS_CLEAN_FILE           : STATUS_CLEAN_FILE,
    STATUS_INFECTED_FILE        : STATUS_INFECTED_FILE,
    STATUS_ERROR_PROCESSING_FILE: STATUS_ERROR_PROCESSING_FILE,
    CLAMAV_DEFINITIONS_FILES    : CLAMAV_DEFINITIONS_FILES
};
